# 特征值特征向量的线线代数几何意义

    我们知道，矩阵乘法对应了一个变换，是把任意一个向量变成另一个方向或长度都大多不同的新向量。在这个变换的过程中，原向量主要发生旋转、伸缩的变化。如果矩阵对某一个向量或某些向量只发生伸缩变换，不对这些向量产生旋转的效果，那么这些向量就称为这个矩阵的特征向量，伸缩的比例就是特征值。
    
    实际上，上述的一段话既讲了矩阵变换特征值及特征向量的几何意义（图形变换）也讲了其物理含义。物理的含义就是运动的图景：特征向量在一个矩阵的作用下作伸缩运动，伸缩的幅度由特征值确定。特征值大于1，所有属于此特征值的特征向量身形暴长；特征值大于0小于1，特征向量身形猛缩；特征值小于0，特征向量缩过了界，反方向到0点那边去了。
    
    关于特征值和特征向量，这里请注意两个亮点。这两个亮点一个是线性不变量的含义，二个是振动的谱含义。  

![206](picture/206.png)

## 例子

![201](picture/201.jpeg)
![202](picture/202.jpeg)
![203](picture/203.jpeg)
![204](picture/204.jpeg)
![205](picture/205.jpeg)

# numpy 求解

In [1]:
import numpy as np

In [3]:
import numpy as np
a = np.array([
    [3, 2, 4],
    [2, 0, 2],
    [4, 2, 3]
])

eigenvalue, featurevector=np.linalg.eig(a)
print(eigenvalue)
print(featurevector)

[-1.  8. -1.]
[[-0.74535599  0.66666667 -0.21539222]
 [ 0.2981424   0.33333333 -0.77010996]
 [ 0.59628479  0.66666667  0.6004472 ]]


In [1]:
import numpy as np
a = np.array([
    [3, 2],
    [2, 0] 
])

eigenvalue, featurevector=np.linalg.eig(a)
print(eigenvalue)
print(featurevector)

[ 4. -1.]
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


In [4]:
a = np.array([
    [1, -2],
    [2, -3] 
])

eigenvalue, featurevector=np.linalg.eig(a)
print(eigenvalue)
print(featurevector)

[-0.99999998 -1.00000002]
[[0.70710678 0.70710678]
 [0.70710678 0.70710678]]
