# 欧式距离

## 介绍等待完善

## 公式实现

###  使用numpy直接实现

In [2]:
import numpy as np

def d_os_1(x, y):
        return np.sqrt(np.sum(np.square(x - y)))

### 使用scipy库实现

In [3]:
import numpy as np
from scipy.spatial.distance import pdist

def d_os_2(x, y):
    X = np.vstack([x, y])
    d = pdist(X)
    return d

In [4]:
x = np.random.random(10)
y = np.random.random(10)

d_os_1(x, y)

1.1751438828851688

In [5]:
d_os_2(x, y)

array([1.17514388])

# 曼哈顿距离

d = |x1 - x2| + |y1 - y2|

## 公式的实现

### 使用numpy直接实现

In [9]:
import numpy as np

def d_mhd_1(x, y):
    return np.sum(np.abs(x - y))

### 使用scipy库实现

In [11]:
import numpy as np
from scipy.spatial.distance import pdist

def d_mhd_2(x, y):
    X = np.vstack([x,y])
    d = pdist(X,'cityblock')
    return d

In [12]:
x = np.random.random(10)
y = np.random.random(10)

d_mhd_2(x, y)

array([3.19424049])

In [13]:
d_mhd_1(x, y)

3.19424049369562

# 3. 切比雪夫距离

## 公式实现

In [14]:
import numpy as np

def d_chebyshev_1(x, y):
    return np.max(np.abs(x-y))

In [15]:
import numpy as np
from scipy.spatial.distance import pdist

def d_chebyshev_2(x, y):
    X = np.vstack([x,y])
    d = pdist(X,'chebyshev')
    return d

In [16]:
x = np.random.random(10)
y = np.random.random(10)

d_chebyshev_2(x, y)

array([0.4630865])

In [17]:
d_chebyshev_1(x, y)

0.4630864970095674

# 闵可夫斯基距离

In [ ]:
#方法一：根据公式求解,p=2
import numpy as np

d_minkowski_1(x, y):
    return np.sqrt(np.sum(np.square(x-y)))

In [19]:
import numpy as np
from scipy.spatial.distance import pdist

def d_minkowski_2(x, y):
    X = np.vstack([x,y])
    d = pdist(X,'minkowski',p=2)
    return d