# 数组操作
- 修改形状
- 翻转操作
- 修改维度
- 数组连接
- 数组分割
- 添加/删除元素

## 1 修改形状
- reshape 不改变数据的条件下修改形状
- flat 数组上的一维迭代器
- flatten 返回折叠为一维的数组副本
- ravel 返回连续的展开数组

In [7]:
import numpy as np 
    
#---------------------------- reshape 不改变数据的条件下修改形状
"""
# numpy.reshape(arr, newshape, order')
这个函数在不改变数据的条件下修改形状，它接受如下参数：
"""
a = np.arange(8)
b = a.reshape(4, 2) 

#---------------------------- flat 数组上的一维迭代器
"""
numpy.ndarray.flat
该函数返回数组上的一维迭代器，行为类似 Python 内建的迭代器。
"""
a = np.arange(8).reshape(2,4) 
b = a.flat[1] 

#---------------------------- flatten 返回折叠为一维的数组副本
"""
ndarray.flatten(order) 
order：'C' — 按行，'F' — 按列，'A' — 原顺序，'k' — 元素在内存中的出现顺序。 

该函数返回折叠为一维的数组副本，函数接受下列参数：
"""
a = np.arange(8).reshape(2,4) 
print(a.flatten()) # [0 1 2 3 4 5 6 7]
print(a.flatten(order = 'F')) # [0 4 1 5 2 6 3 7]


#---------------------------- ravel 返回连续的展开数组
"""
numpy.ravel(a, order) 
order：'C' — 按行，'F' — 按列，'A' — 原顺序，'k' — 元素在内存中的出现顺序。 

这个函数返回展开的一维数组，并且按需生成副本。返回的数组和输入数组拥有相同数据类型。这个函数接受两个参数。
"""
a = np.arange(8).reshape(2,4) 
print(a.ravel()) # [0 1 2 3 4 5 6 7]
print(a.ravel(order = 'F')) # [0 4 1 5 2 6 3 7]

[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]
[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]


## 2 翻转操作

- transpose 翻转数组的维度
- ndarray.T和self.transpose()相同
- rollaxis 向后滚动指定的轴
- swapaxes 互换数组的两个轴

In [17]:
import numpy as np

#---------------------------- transpose 翻转数组的维度
"""
numpy.transpose(arr, axes) 
- arr：要转置的数组
- axes：整数的列表，对应维度，通常所有维度都会翻转。

这个函数翻转给定数组的维度。如果可能的话它会返回一个视图。函数接受下列参数：
"""
a = np.arange(12).reshape(3,4)
"""
print(a)
print(np.transpose(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
"""

#---------------------------- ndarray.T和self.transpose()相同
"""
该函数属于ndarray类，行为类似于numpy.transpose。
"""
a = np.arange(12).reshape(3,4) 
"""
print(a)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
"""

#---------------------------- rollaxis 向后滚动指定的轴
"""
numpy.rollaxis(arr, axis, start)
- arr：输入数组
- axis：要向后滚动的轴，其它轴的相对位置不会改变
- start：默认为零，表示完整的滚动。会滚动到特定位置。

该函数向后滚动特定的轴，直到一个特定位置。
"""

a = np.arange(8).reshape(2,2,2) 
"""
print(a)
print(np.rollaxis(a, 2)) # 将轴 2 滚动到轴 0(宽度到深度)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
"""

#---------------------------- swapaxes 互换数组的两个轴
"""
numpy.swapaxes(arr, axis1, axis2) 
- arr：要交换其轴的输入数组
- axis1：对应第一个轴的整数
- axis2：对应第二个轴的整数 

该函数交换数组的两个轴。
"""
a = np.arange(4).reshape(2,2)
"""
print(a)
print(np.swapaxes(a, 1, 0))

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]
"""

print()

## 3 修改维度

- broadcast 产生模仿广播的对象
- broadcast_to 将数组广播到新形状
- expand_dims 扩展数组的形状
- squeeze 从数组的形状中删除单维条目


In [33]:
import numpy as np

#---------------------------- broadcast 产生模仿广播的对象
"""
broadcast

如前所述，NumPy 已经内置了对广播的支持。
此功能模仿广播机制。 它返回一个对象，
该对象封装了将一个数组广播到另一个数组的结果。 
"""
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])  
b = np.broadcast(x, y) 
print(b.shape)   # (3, 3)
 
#---------------------------- broadcast_to 将数组广播到新形状
"""
numpy.broadcast_to(array, shape, subok) 

此函数将数组广播到新形状。 它在原始数组上返回只读视图。
它通常不连续。 如果新形状不符合 NumPy 的广播规则，该函数可能会抛出ValueError。 
"""
a = np.arange(4).reshape(1,4) 
"""
print(a)
print(np.broadcast_to(a, (4, 4)))

[[0 1 2 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
"""

#---------------------------- expand_dims 扩展数组的形状
"""
numpy.expand_dims(arr, axis)
- arr：输入数组
- axis：新轴插入的位置

函数通过在指定位置插入新的轴来扩展数组形状
"""
x = np.array(([1,2],[3,4])) 
"""
print(x)
print(np.expand_dims(x, axis=2))

[[1 2]
 [3 4]]
[[[1]
  [2]]

 [[3]
  [4]]]
"""

#---------------------------- squeeze 从数组的形状中删除单维条目
"""
numpy.squeeze(arr, axis) 
- arr：输入数组
- axis：整数或整数元组，用于选择形状中单一维度条目的子集

函数从给定数组的形状中删除一维条目
"""
x = np.arange(9).reshape(1,3,3) 
"""
print(x.shape)
print(np.squeeze(x).shape)

(1, 3, 3)
(3, 3)
"""

print()

(3, 3)



## 4 数组连接

- concatenate 沿着现存的轴连接数据序列
- srack 沿着新轴连接数组序列
- hstack 水平堆叠序列中的数组(列方向)
- vastack 竖直堆叠序列中的数组(行方向)


In [37]:
import numpy as np

#---------------------------- sconcatenate 沿着现存的轴连接数据序列
"""
numpy.concatenate((a1, a2, ...), axis) 
- a1, a2, ...：相同类型的数组序列
- axis：沿着它连接数组的轴，默认为 0

数组的连接是指连接。 此函数用于沿指定轴连接相同形状的两个或多个数组
"""
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
"""
print(np.concatenate((a, b)))
print(np.concatenate((a, b), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
"""

#---------------------------- ssrack 沿着新轴连接数组序列
"""
numpy.stack(arrays, axis) 
- arrays：相同形状的数组序列
- axis：返回数组中的轴，输入数组沿着它来堆叠

此函数沿新轴连接数组序列。
"""
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
"""
print(np.stack((a, b), 0))
print(np.stack((a, b), 1))

第一个数组：
[[1 2]
 [3 4]]

第二个数组：
[[5 6]
 [7 8]]

沿轴 0 堆叠两个数组：
[[[1 2]
 [3 4]]
 [[5 6]
 [7 8]]]

沿轴 1 堆叠两个数组：
[[[1 2]
 [5 6]]
 [[3 4]
 [7 8]]] 
"""

#---------------------------- shstack 水平堆叠序列中的数组(列方向)
"""
numpy.stack函数的变体，通过堆叠来生成水平的单个数组。
"""
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
"""
print(np.hstack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]
"""

#---------------------------- svastack 竖直堆叠序列中的数组(行方向)
"""
numpy.stack函数的变体，通过堆叠来生成竖直的单个数组。
"""
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
"""
print(np.vstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
"""

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


'\nprint(np.hstack((a, b)))\n\n[[1 2 5 6]\n [3 4 7 8]]\n'

## 5 数组分割

- split 将一个数组分割为多个子数组
- hsplit 将一个数组水平分割为多个子数组(按列)
- vsplit 将一个数组竖直分割为多个子数组(按行)


In [44]:
import numpy as np

#---------------------------- split 将一个数组分割为多个子数组
"""
numpy.split(ary, indices_or_sections, axis)
- ary：被分割的输入数组
- indices_or_sections：可以是整数，表明要从输入数组创建的，等大小的子数组的数量。 如果此参数是一维数组，则其元素表明要创建新子数组的点。
- axis：默认为 0 

该函数沿特定的轴将数组分割为子数组
"""
a = np.arange(9) 
# '将数组分为三个大小相等的子数组：'
print(np.split(a, 3)) # [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
# 将数组在一维数组中表明的位置分割：
print(np.split(a, [4, 7])) # [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

#---------------------------- hsplit 将一个数组水平分割为多个子数组(按列)
"""
numpy.hsplit是split()函数的特例，其中轴为 1 表示水平分割，无论输入数组的维度是什么。
"""
a = np.arange(16).reshape(4, 4)
print(np.hsplit(a, 2)) # 水平分割
"""
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), 
       
array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
"""

#---------------------------- vsplit 将一个数组竖直分割为多个子数组(按行)
"""
numpy.vsplit是split()函数的特例，其中轴为 0 表示竖直分割，无论输入数组的维度是什么 
"""
a = np.arange(16).reshape(4, 4)
print(np.vsplit(a, 2))
"""
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), 
       
array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
"""


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## 6 添加/删除元素

- resize 返回指定形状的新数组
- append 将值添加到数组末尾
- insert 沿指定轴将值插入到指定下标之前
- delete 返回删掉某个轴的子数组的新数组
- unique 寻找数组内的唯一元素


In [75]:
import numpy as np

#---------------------------- resize 返回指定形状的新数组
"""
numpy.resize(arr, shape)
- arr：要修改大小的输入数组
- shape：返回数组的新形状

此函数返回指定大小的新数组。 如果新大小大于原始大小，则包含原始数组中的元素的重复副本。 
"""
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape) # (2, 3)
"""
print(np.resize(a, (2, 3)))
[[1 2]
 [3 4]
 [5 6]]
 
print(np.resize(a, (2, 2)))
 [[1 2]
 [3 4]]
 
print(np.resize(a, (3, 3)))
 [[1 2 3]
 [4 5 6]
 [1 2 3]]
"""

#---------------------------- append 将值添加到数组末尾
"""
numpy.append(arr, values, axis)
- arr：输入数组
- values：要向arr添加的值，比如和arr形状相同(除了要添加的轴)
- axis：沿着它完成操作的轴。如果没有提供，两个参数都会被展开。 

此函数在输入数组的末尾添加值。 附加操作不是原地的，而是分配新的数组。
此外，输入数组的维度必须匹配否则将生成ValueError。 
"""
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.append(a, [7, 8, 9]))  # [1 2 3 4 5 6 7 8 9] 向数组添加元素
"""
print(np.append(a, [[7, 8, 9]], axis=0))  # 沿轴 0 添加元素

[[1 2 3]
 [4 5 6]
 [7 8 9]]
"""
"""
print(np.append(a, [[5],[7]], axis=1))  # 沿轴 1 添加元素

[[1 2 3 5]
 [4 5 6 7]]
"""

#---------------------------- insert 沿指定轴将值插入到指定下标之前
"""
numpy.insert(arr, obj, values, axis) 
- arr：输入数组
- obj：在其之前插入值的索引
- values：要插入的值
- axis：沿着它插入的轴，如果未提供，则输入数组会被展开 

此函数在给定索引之前，沿给定轴在输入数组中插入值。
如果值的类型转换为要插入，则它与输入数组不同。 插入没有原地的，函数会返回一个新数组。
此外，如果未提供轴，则输入数组会被展开。 
"""
a = np.array([[1, 2], [3, 4], [5, 6]])
# '未传递 Axis 参数。 在插入之前输入数组会被展开。'
print(np.insert(a, 3, [11, 12])) # [ 1  2  3 11 12  4  5  6]
"""
print(np.insert(a, 1, [11], axis=0)) # 沿轴 0 广播

[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
"""

"""
print(np.insert(a, 1, 11, axis=1)) # 沿轴 1 广播：

[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]
"""


#---------------------------- delete 返回删掉某个轴的子数组的新数组
"""
Numpy.delete(arr, obj, axis) 
- arr：输入数组
- obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组
- axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开 

此函数返回从输入数组中删除指定子数组的新数组。 
与insert()函数的情况一样，如果未提供轴参数，则输入数组将展开。 
"""
a = np.arange(12).reshape(3, 4)

# 未传递 Axis 参数。 在删除之前输入数组会被展开。'
print(np.delete(a, 5)) # [ 0  1  2  3  4  6  7  8  9 10 11]

"""
# 删除第二列
print(np.delete(a,1,axis = 1))

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
"""

#---------------------------- unique 寻找数组内的唯一元素
"""
numpy.unique(arr, return_index, return_inverse, return_counts) 
- arr：输入数组，如果不是一维数组则会展开
- return_index：如果为true，返回输入数组中的元素下标
- return_inverse：如果为true，返回去重数组的下标，它可以用于重构输入数组
- return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数

此函数返回输入数组中的去重元素数组。 
该函数能够返回一个元组，包含去重数组和相关索引的数组。
索引的性质取决于函数调用中返回参数的类型。 
"""
a = np.array([5,2,6,2,7,5,6,8,2,9, 20]) 
print(np.unique(a)) # 去重数
# 去重数组的索引数组
print(np.unique(a, return_index=True)) # (array([ 2,  5,  6,  7,  8,  9, 20]), array([ 1,  0,  2,  4,  7,  9, 10]))
# 去重数组的下标
print(np.unique(a, return_inverse=True)) # (array([ 2,  5,  6,  7,  8,  9, 20]), array([1, 0, 2, 0, 3, 1, 2, 4, 0, 5, 6]))

(2, 3)
[1 2 3 4 5 6 7 8 9]
[ 1  2  3 11 12  4  5  6]
[ 0  1  2  3  4  6  7  8  9 10 11]
[ 2  5  6  7  8  9 20]
(array([ 2,  5,  6,  7,  8,  9, 20]), array([ 1,  0,  2,  4,  7,  9, 10]))
(array([ 2,  5,  6,  7,  8,  9, 20]), array([1, 0, 2, 0, 3, 1, 2, 4, 0, 5, 6]))
