# 线性代数
- dot 两个数组的点积
- vdot 两个向量的内积
- inner 两个数组的矩阵积
- matmul 两个数组的矩阵积 
- solv 求解线性方程式
- inv 寻找矩阵的乘法矩阵

In [7]:
import numpy as np

#----------------------- dot 两个数组的点积
"""
numpy.dot()

此函数返回两个数组的点积。 
对于二维向量，其等效于矩阵乘法。
对于一维数组，它是向量的内积。 
对于 N 维数组，它是a的最后一个轴上的和与b的倒数第二个轴的乘积。 
"""
a = np.array([[1, 2], [3, 4]])
b = np.array([[11, 12], [13, 14]])
"""
print(np.dot(a, b))
注意点积的计算为
[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]


[[37 40]
 [85 92]]
"""

#----------------------- vdot 两个向量的内积
"""
numpy.vdot()

此函数返回两个向量的点积。
如果第一个参数是复数，那么它的共轭复数会用于计算。 
如果参数id是多维数组，它会被展开。 
"""
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
"""
print(np.vdot(a,b))

1*11 + 2*12 + 3*13 + 4*14 = 130

130
"""

#----------------------- inner 两个数组的矩阵积
"""
numpy.inner()

此函数返回一维数组的向量内积。 对于更高的维度，它返回最后一个轴上的和的乘积。
"""
print(np.inner(np.array([1,2,3]),np.array([0,1,0])) )
# 等价于 1*0+2*1+3*0 = 2

a = np.array([[1,2], [3,4]])  
b = np.array([[11, 12], [13, 14]])  
"""
print(np.inner(a, b))

1*11+2*12, 1*13+2*14 
3*11+4*12, 3*13+4*14 

[[35 41]
 [81 95]]
"""

#----------------------- matmul 两个数组的矩阵积
"""
numpy.matmul

numpy.matmul()函数返回两个数组的矩阵乘积。 
虽然它返回二维数组的正常乘积，但如果任一参数的维数大于2，
则将其视为存在于最后两个索引的矩阵的栈，并进行相应广播。 
"""
a = [[1,0],[1,1]] 
b = [[4,1],[2,2]] 
"""
print(np.matmul(a, b) )

[[1, 0],
 [1, 1]]
[[4, 1],
 [2, 2]]
# 过程
1*4+0*2 1*1+0*2
1*4+1*2 1*1+1*2

[[4 1]
 [6 3]]
"""
a = [[1,0],[0,1]] 
b = [1,2] 
"""
print(np.matmul(a,b))
print(np.matmul(b,a))

[1 2]
[1 2]
""" 

2
[1 2]
[1 2]
