In [5]:
import pandas as pd

In [6]:
path = "/Users/zhouwencheng/Desktop/Grass/05 AI/06 data/10 data/01 文本/其他/toutiao_cat_data.txt"
# path = "/Users/zhouwencheng/Desktop/Grass/05 AI/06 data/10 data/01 文本/其他/t_test.txt"

df = pd.read_csv(path,  sep='_!_',  header = None ,engine = 'python')

df.tail()



0    1                 2  \
382683  6554578634403741966  109         news_tech   
382684  6554623450374209806  110     news_military   
382685  6554489948580348424  113        news_world   
382686  6554706019040100611  113        news_world   
382687  6554360505438306824  115  news_agriculture   

                                      3                       4  
382683          A10处理器iPhone SE二代值得期待吗？                     NaN  
382684  先进战机叛逃将带来重大损失，美军如何防止F22飞行员驾机叛逃？                     NaN  
382685    又一国领导人放话，只要普京下令，数万大军“碾压”美国白宫！       以色列,普京,俄罗斯,叙利亚,车臣  
382686        如何看待美国总统连续撕毁美国签署的国际协议的举动？                     NaN  
382687           农博会上，公安100余种土特产成了抢手货……  特色农产品,农博会,荆州市,生物科技,公安县

In [7]:
df.columns = ['Num', 'class_no', 'type', 'content', 'words']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 382688 entries, 0 to 382687
Data columns (total 5 columns):
Num         382688 non-null int64
class_no    382688 non-null int64
type        382688 non-null object
content     382688 non-null object
words       260235 non-null object
dtypes: int64(2), object(3)
memory usage: 14.6+ MB


In [8]:
df.type.unique()

array(['news_culture', 'news_entertainment', 'news_sports',
       'news_finance', 'news_house', 'news_car', 'news_edu', 'news_tech',
       'news_military', 'news_travel', 'news_world', 'news_agriculture',
       'news_game', 'stock', 'news_story'], dtype=object)

# 进行分词处理
- 这里采用结巴分词处理

In [9]:
# 进行分词处理
import jieba

In [10]:
# 结巴分词测试
test_text = pd.Series(data = ["这是这样的是爱你是说说就是", "我都记单词的吧是残次"])
test_text = test_text.values.tolist()
s1 = test_text[0] 
## 需要转化成list形式
cut_text = jieba.lcut(s1) 
cut_text

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/tr/450bmr9s7_j0cxc2cltz_q2w0000gn/T/jieba.cache
Loading model cost 1.194 seconds.
Prefix dict has been built succesfully.


['这是', '这样', '的', '是', '爱', '你', '是', '说', '说', '就是']

In [11]:
df.head()

Num  class_no          type                    content  \
0  6551700932705387022       101  news_culture           京城最值得你来场文化之旅的博物馆   
1  6552368441838272771       101  news_culture          发酵床的垫料种类有哪些？哪种更好？   
2  6552407965343678723       101  news_culture      上联：黄山黄河黄皮肤黄土高原。怎么对下联？   
3  6552332417753940238       101  news_culture  林徽因什么理由拒绝了徐志摩而选择梁思成为终身伴侣？   
4  6552475601595269390       101  news_culture                   黄杨木是什么树？   

                      words  
0  保利集团,马未都,中国科学技术馆,博物馆,新中国  
1                       NaN  
2                       NaN  
3                       NaN  
4                       NaN

In [12]:
def cut_content(contents):
    cut_content = [] 
    for line in contents:
        cut_line = jieba.lcut(line) 
        cut_content.append(cut_line) 
    return cut_content 
cut_contens = cut_content(df.content) 

In [13]:
df.content = cut_contens
df.head()

Num  class_no          type  \
0  6551700932705387022       101  news_culture   
1  6552368441838272771       101  news_culture   
2  6552407965343678723       101  news_culture   
3  6552332417753940238       101  news_culture   
4  6552475601595269390       101  news_culture   

                                             content                     words  
0                 [京城, 最, 值得, 你, 来场, 文化, 之旅, 的, 博物馆]  保利集团,马未都,中国科学技术馆,博物馆,新中国  
1          [发酵, 床, 的, 垫料, 种类, 有, 哪些, ？, 哪, 种, 更好, ？]                       NaN  
2        [上联, ：, 黄山, 黄河, 黄皮肤, 黄土高原, 。, 怎么, 对, 下联, ？]                       NaN  
3  [林徽因, 什么, 理由, 拒绝, 了, 徐志摩, 而, 选择, 梁思成, 为, 终身伴侣, ？]                       NaN  
4                                 [黄杨木, 是, 什么, 树, ？]                       NaN

# 去掉停词

In [15]:
# 获取停词

stop_path = "/Users/zhouwencheng/Desktop/Grass/05 AI/06 data/10 data/01 文本/stopwords.txt"
stopwords = pd.read_csv(stop_path, index_col=False, sep="\t",quoting=3,names=['stopword'], encoding='utf-8')
stopwords.head() 

stopword
0        !
1        "
2        #
3        $
4        %

In [16]:
def cut_of_stop_word(sentence, stop_words):
    content_s = []
    all_words = []
    for line in df.content:
        sentence = []
        for word in line:
            if word not in stop_words:
                sentence.append(word)
                all_words.append(word)
        content_s.append(sentence)
    return content_s, all_words
        
stop_words = stopwords.stopword.values.tolist()
content_s, all_words = cut_of_stop_word(df.content, stop_words)
df.content = content_s

df.head()

Num  class_no          type  \
0  6551700932705387022       101  news_culture   
1  6552368441838272771       101  news_culture   
2  6552407965343678723       101  news_culture   
3  6552332417753940238       101  news_culture   
4  6552475601595269390       101  news_culture   

                             content                     words  
0          [京城, 值得, 来场, 文化, 之旅, 博物馆]  保利集团,马未都,中国科学技术馆,博物馆,新中国  
1                [发酵, 床, 垫料, 种类, 更好]                       NaN  
2        [上联, 黄山, 黄河, 黄皮肤, 黄土高原, 下联]                       NaN  
3  [林徽因, 理由, 拒绝, 徐志摩, 选择, 梁思成, 终身伴侣]                       NaN  
4                           [黄杨木, 树]                       NaN

In [17]:
all_words=pd.DataFrame({'all_words':all_words})
all_words.head()

all_words
0        京城
1        值得
2        来场
3        文化
4        之旅

In [19]:
word_counts =  all_words.all_words.value_counts()
word_counts.head()

      53055
中国    17050
美国    10913
上联    10138
下联     9987
Name: all_words, dtype: int64

# 词袋

In [20]:
# 测试

from sklearn.feature_extraction.text import CountVectorizer
texts=["dog cat fish","dog cat cat","fish bird", 'bird']
cv = CountVectorizer()
cv_fit=cv.fit_transform(texts)

cv_fit.toarray()

array([[0, 1, 1, 1],
       [0, 2, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 0]], dtype=int64)

In [21]:
words = []
for line_index in range(len(df.content)):
    try: 
        words.append(' '.join(df.content[line_index]))
    except:
        print (line_index,word_index)

['京城 值得 来场 文化 之旅 博物馆',
 '发酵 床 垫料 种类 更好',
 '上联 黄山 黄河 黄皮肤 黄土高原 下联',
 '林徽因 理由 拒绝 徐志摩 选择 梁思成 终身伴侣',
 '黄杨木 树',
 '上联 草根 登上 星光 道 下联',
 '超 写实 绘画',
 '松涛 听雨莺 婉转 下联',
 '上联 老子 骑牛 读书 下联',
 '上联 山水 醉人 酒 下联',
 '国画 山水 读懂 山水画',
 '一元 硬币 价值 24000 元 找找看',
 '感动 语句',
 '上联 绿竹 引 清风 下联',
 '赵 宁安 作品 欣赏',
 '夕阳 无语 燕归愁 接下 句',
 '上联 山水 醉人 酒 下联',
 '上联 上班 下班 下联',
 '下联 夕陽 西下 黄昏 上联 什 麽',
 '初夏 方好 小荷 初露 读 美不胜收 咏 荷 经典 诗词',
 '谢娜 李浩菲 澄清 网络 谣言 两个 加',
 '谢娜 主办方 撕破脸 谢娜 复出 快本 第一个 到场 支持',
 '中国 网红竟 红到 美国 不多 说 连小编 心动',
 '赵丽颖 很久没 登上 微博热 搜 别急 憋 大招',
 '因戴 眼镜 改变 气质 娱乐圈 明星 喜欢',
 '抢先',
 '超级 英雄 演员 颜值 身材 排名 钢铁 侠 进不了 前 第一名 意外',
 '无限 歌谣 季 热播   张绍 刚毛 不易 组合 似 父子',
 '张靓颖 透露 右耳 间歇性 失聪',
 '成龙 改口 不裸 捐 亿 财产 儿子 一半',
 '五大 出轨 女明星 肯定',
 '搞笑 男人 最帅 大张伟 张嘴 美男子 蜜汁 好看',
 '谢娜 喜临门 何炅 送祝福 吴昕 送祝福 沈梦辰',
 '评价 赵丽颖',
 '偏 冷门 歌曲 推荐',
 '整容 狂人 审美 恕 欣赏',
 '杨幂 景甜 徐 冬冬 唐嫣   好好 穿衣 美的 有趣 撩人',
 '吴卓林 父母 责任 责任',
 '天乩 战 白蛇传 说 赵雅芝 杨 紫 饰演 母女 擦 火花',
 '最帅 反派 专业户 演 古惑仔 大火 病魔缠身 可怜 无人 识',
 '亚洲杯 夺冠 赔率 日本 伊朗 领衔   中国 泰国 并列',
 '轮 球 本土 射手 仅次 武磊   黄紫昌要 抢 最强 U23 头衔',
 '勇士 夺冠 赛季 詹姆斯 何去何从',
 '超级 

In [22]:
df['content_join'] = words
df.head()

Num  class_no          type  \
0  6551700932705387022       101  news_culture   
1  6552368441838272771       101  news_culture   
2  6552407965343678723       101  news_culture   
3  6552332417753940238       101  news_culture   
4  6552475601595269390       101  news_culture   

                             content                     words  \
0          [京城, 值得, 来场, 文化, 之旅, 博物馆]  保利集团,马未都,中国科学技术馆,博物馆,新中国   
1                [发酵, 床, 垫料, 种类, 更好]                       NaN   
2        [上联, 黄山, 黄河, 黄皮肤, 黄土高原, 下联]                       NaN   
3  [林徽因, 理由, 拒绝, 徐志摩, 选择, 梁思成, 终身伴侣]                       NaN   
4                           [黄杨木, 树]                       NaN   

                content_join  
0         京城 值得 来场 文化 之旅 博物馆  
1              发酵 床 垫料 种类 更好  
2       上联 黄山 黄河 黄皮肤 黄土高原 下联  
3  林徽因 理由 拒绝 徐志摩 选择 梁思成 终身伴侣  
4                      黄杨木 树

In [1]:
import pandas as pd

path = "/Users/zhouwencheng/Desktop/Grass/05 AI/06 data/10 data/01 文本/其他/s_join.txt"
df = pd.read_csv(path)
# df.head()
# type_mapping = {
#     "news_culture": 1, 
#     "news_entertainment": 2, 
#     "news_sports": 3, 
#     "news_finance": 4, 
#     "news_house":5, 
#     "news_car": 6,
#     "news_edu": 7,
#     "news_tech": 8,
#     "news_military": 9,
#     "news_travel": 10,
#     "news_world": 11,
#     "news_agriculture": 12,
#     "news_game": 13,
#     "stock": 14,
#     "news_story": 15, 
# }

# df['type_num'] = df['type'].map(type_mapping)
df.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1                  Num  class_no  \
0           0             0               0  6551700932705387022       101   
1           1             1               1  6552368441838272771       101   
2           2             2               2  6552407965343678723       101   
3           3             3               3  6552332417753940238       101   
4           4             4               4  6552475601595269390       101   

           type                                          content  \
0  news_culture            ['京城', '值得', '来场', '文化', '之旅', '博物馆']   
1  news_culture                    ['发酵', '床', '垫料', '种类', '更好']   
2  news_culture          ['上联', '黄山', '黄河', '黄皮肤', '黄土高原', '下联']   
3  news_culture  ['林徽因', '理由', '拒绝', '徐志摩', '选择', '梁思成', '终身伴侣']   
4  news_culture                                     ['黄杨木', '树']   

                      words               content_join  type_num  
0  保利集团,马未都,中国科学技术馆,博物馆,新中国         京城 值得 来场 文化 之旅 博物馆         1  
1                       NaN              发酵 床 垫料 种类 更好         1  
2                       NaN       上联 黄山 黄河 黄皮肤 黄土高原 下联         1  
3                       NaN  林徽因 理由 拒绝 徐志摩 选择 梁思成 终身伴侣         1  
4                       NaN                      黄杨木 树         1

In [2]:
import numpy as np

words = df.content_join[1:].values.tolist()
# words = df.content_join.values.tolist()
len(words)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 382688 entries, 0 to 382687
Data columns (total 10 columns):
Unnamed: 0        382688 non-null int64
Unnamed: 0.1      382688 non-null int64
Unnamed: 0.1.1    382688 non-null int64
Num               382688 non-null int64
class_no          382688 non-null int64
type              382688 non-null object
content           382688 non-null object
words             260235 non-null object
content_join      382688 non-null object
type_num          382688 non-null int64
dtypes: int64(6), object(4)
memory usage: 29.2+ MB


In [3]:
# words = [ '我国 进口 国外 大豆 用到 完才 明白',
#  '植物 喷施 硫酸亚铁 浓度 合适',
#  '稻种 缺陷 水稻 减产',
#  '小记 记忆 中 温暖 时光']
words = df.content_join.values.tolist()
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv_fit=cv.fit_transform(words) 

x = cv_fit.toarray() 

x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# 贝叶斯分类

In [8]:
y = df.type_num.values.ravel()
y

array([ 1,  1,  1, ..., 11, 11, 12])

In [9]:
begin = -5000
train_num = 5000

x_train = x[:train_num] # 前140
y_train = y[:train_num]
x_test = x[begin:]
y_test = y[begin:]

print(len(x_train))
print(len(y_train))
print(len(x_test))
print(len(y_test)) 

5000
5000
5000
5000


In [12]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
def 

In [11]:
classifier.score(x_test , y_test)

0.712