In [29]:
# 文本处理

import jieba

text_1 = "这只皮靴号码大了。那只号码合适"
text_2 = "这只皮靴号码不小，那只更合适"

# 进行分词处理
t1_list = list(jieba.cut(text_1))
t2_list = list(jieba.cut(text_2))

# 构建 index word 字典
words = set(t1_list + t2_list)
word_to_index = {word:index for index, word in enumerate(words)} 
index_to_word = {index:word for index, word in enumerate(words)} 

# 把词转化成index
def bag_of_word(sentence, word_to_index=word_to_index):
    words_num = len(word_to_index)
    index_list = [0  for _ in range(words_num)]
    for word in sentence:
        index = word_to_index.get(word, 0)
        index_list[index] += 1
    return index_list
    

t1_index = bag_of_word(t1_list)
t2_index = bag_of_word(t2_list)

import numpy as np


t1_list = np.array(t1_list)
t2_list = np.array(t2_list)

t1_index = np.array(t1_index)
t2_index = np.array(t2_index)

print(t1_index)
print(t2_index)

[1 1 1 0 2 1 1 1 0 1 2 0]
[1 0 0 1 2 0 1 1 1 1 1 1]


# 1 余弦相似度

In [2]:
# 自定义实现

def cosine_similarity(vector1, vector2):
    dot_product = 0.0
    normA = 0.0
    normB = 0.0
    for a, b in zip(vector1, vector2):
        dot_product += a * b
        normA += a ** 2
        normB += b ** 2
    if normA == 0.0 or normB == 0.0:
        return 0
    else:
        return round(dot_product / ((normA**0.5)*(normB**0.5)) * 100, 2)
    
cosine_similarity(t1_index, t2_index)

74.54

In [3]:
# sklearn 里面的实现

from sklearn.metrics.pairwise import cosine_similarity 
cosine_similarity([t1_index, t2_index])

array([[1.        , 0.74535599],
       [0.74535599, 1.        ]])

# 2 欧式距离

In [11]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances([t1_index, t2_index])

array([[0.        , 2.64575131],
       [2.64575131, 0.        ]])

In [15]:
import numpy as np
np.sqrt(np.sum(np.square(np.array(t1_index)-np.array(t2_index))))

2.6457513110645907

In [20]:
from scipy.spatial.distance import pdist
X=np.vstack([t1_index, t2_index])  
pdist(X) 

array([2.64575131])

# 3 曼哈顿距离

In [23]:
from numpy import *
abs(mat(t1_index)-mat(t2_index))

matrix([[0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1]])

In [28]:
sum(abs(np.array(t1_index)-np.array(t2_index)))

7

# 4 皮尔森相似度

"文本的皮尔森相似度:":np.sum(a*b) / (np.sqrt(np.sum(a ** 2)) * np.sqrt(np.sum(b ** 2)))


In [30]:
a = t1_index
b = t2_index
np.sum(a*b) / (np.sqrt(np.sum(a ** 2)) * np.sqrt(np.sum(b ** 2)))

0.74535599249993

# 5 Jaccard相似性系数
计算sa和sb的相似度 len（sa & sb）/ len（sa | sb）

In [34]:
seta = set(t1_list)
setb = set(t2_list)

print(f"seta:{seta}")
print(f"setb:{setb}")


1.0 * len(seta & setb) / len(seta | setb)

seta:{'合适', '。', '了', '只', '大', '这', '那', '皮靴', '号码'}
setb:{'合适', '，', '只', '这', '那', '不小', '皮靴', '号码', '更'}


0.5