<font size = 5>numpy and torch</font>

In [3]:
import torchm
import numpy as np

# convert numpy to tensor or vist versa

In [5]:
# convert numpy to tensor or vist versa
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()

print(
    '\nnumpy array:\n', np_data,
    '\ntorch tensor:\n', torch_data,
    '\ntensor to array:\n',tensor2array
)


numpy array:
 [[0 1 2]
 [3 4 5]] 
torch tensor:
 tensor([[0, 1, 2],
        [3, 4, 5]]) 
tensor to array:
 [[0 1 2]
 [3 4 5]]


# abs- 绝对值

In [6]:
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)
print(
    '\nabs',
    '\nnumpy:', np.abs(data),
    '\ntorch', torch.abs(tensor)
)


abs 
numpy: [1 2 1 2] 
torch tensor([1., 2., 1., 2.])


# sin

In [8]:
print(
    '\nsin',
    '\nnumpy:', np.sin(data),
    '\ntorch:', torch.sin(tensor)
)


sin 
numpy: [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch: tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [9]:
tensor.sigmoid()

tensor([0.2689, 0.1192, 0.7311, 0.8808])

In [10]:
tensor.exp()

tensor([0.3679, 0.1353, 2.7183, 7.3891])

# mean

In [11]:
print(
    '\nmean',
    '\nnumpy:', np.mean(data),
    '\ntorch:', torch.mean(tensor)
)


mean 
numpy: 0.0 
torch: tensor(0.)


# matrix multiplication

In [13]:
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)

print(
    '\nmatrix multiplication (matmul)',
    '\nnumpy:\n', np.matmul(data, data),
    '\ntorch:\n', torch.mm(tensor, tensor)
)


matrix multiplication (matmul) 
numpy:
 [[ 7 10]
 [15 22]] 
torch:
 tensor([[ 7., 10.],
        [15., 22.]])


In [14]:
tensor.mm(tensor)

tensor([[ 7., 10.],
        [15., 22.]])

In [15]:
tensor*tensor

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [21]:
# 好像只能是一维的才能用dot
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

tensor(7)