In [2]:
import torch
from torch.autograd import Variable

In [12]:
tensor = torch.FloatTensor([[1, 2], [3, 4]])
varible = Variable(tensor, requires_grad=True)
print(tensor)
print(varible)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [13]:
t_out = torch.mean(tensor*tensor) # x^2
v_out = torch.mean(varible*varible)

print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [14]:
v_out.backward()

# v_out = 1/4*sum(var*var)
# d(v_out)/d(var) = 1/4*2*variable = variable/2

print(varible.grad)


tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [15]:
print(varible)
print(varible.data)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
