# 创建数组

- 空数组
  - empty 空数组
  - zeros 以0为填充的数组
  - ones 以1为填充的数组
- 现有数据的数组
  - asarray （列表、列表的元组、元组、元组的元组、元组的列表）
- 来自数据范围
  - arange
  - linspace
  - logspace
- 随机生成 np.random

## 1 空数组

 创建一个不带数据的，或者带有0、1等初始化的数组
 
- empty 空数组
- zeros 以0为填充的数组
- ones 以1为填充的数组

In [9]:
#---------------------- empty 空数组
"""
numpy.empty(shape, dtype = float, order = 'C')

- Shape 空数组的形状，整数或整数元组
- Dtype 所需的输出数组类型，可选
- Order 'C'为按行的 C 风格数组，'F'为按列的 Fortran 风格数组 
"""
import numpy as np 
x = np.empty([3,2], dtype =  int)  
"""
print(x)

[[0 0]
 [0 0]
 [0 0]]
"""

#--------------------- numpy.zeros
"""
返回特定大小，以 0 填充的新数组。

numpy.zeros(shape, dtype = float, order = 'C')

- Shape 空数组的形状，整数或整数元组
- Dtype 所需的输出数组类型，可选
- Order 'C'为按行的 C 风格数组，'F'为按列的 Fortran 风格数组 
"""
## 示例-1  含有 5 个 0 的数组，默认类型为 float  
import numpy as np 
x = np.zeros(5)  
"""
print(x)

[0. 0. 0. 0. 0.]
"""

# 示例- 2
import numpy as np 
x = np.zeros((5,), dtype = np.int)  
"""
print(x)

[0 0 0 0 0]
"""

# 示例- 3
import numpy as np 
x = np.zeros((2,2), dtype =  [('x',  'i4'),  ('y',  'i4')])   
"""
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
"""

#----------------------- numpy.ones
"""
返回特定大小，以 1 填充的新数组。

numpy.ones(shape, dtype = None, order = 'C')

- Shape 空数组的形状，整数或整数元组
- Dtype 所需的输出数组类型，可选
- Order 'C'为按行的 C 风格数组，'F'为按列的 Fortran 风格数组 
"""

# 含有 5 个 1 的数组，默认类型为 float  
import numpy as np 
x = np.ones(5) 
"""
print(x)

[1. 1. 1. 1. 1.]
"""

import numpy as np 
x = np.ones([2,2], dtype =  int)  
"""
print(x)

[[1 1]
 [1 1]]
"""

print()

## 现有数据的数组

numpy也可以用现有的列表、元组等数据来转化为ndarray

- asarray （列表、列表的元组、元组、元组的元组、元组的列表）

In [14]:
#--------------------- asarray
"""
此函数类似于numpy.array，除了它有较少的参数。 这个例程对于将 Python 序列转换为ndarray非常有用。 

numpy.asarray(a, dtype = None, order = None)

- a 任意形式的输入参数，比如列表、列表的元组、元组、元组的元组、元组的列表
- dtype 通常，输入数据的类型会应用到返回的ndarray
- order 'C'为按行的 C 风格数组，'F'为按列的 Fortran 风格数组
"""
import numpy as np 

print(np.asarray([1, 2, 3])) # 把列表转化ndarray
print(np.asarray([1, 2, 3], dtype=float)) # 把列表转化ndarray (类型转化为float)
print(np.asarray((1, 2, 3))) # 把元组转化ndarray
print(np.asarray([(1,2,3),(4,5)] )) # 把元组列表转化为ndarray

[1 2 3]
[1. 2. 3.]
[1 2 3]
[(1, 2, 3) (4, 5)]


## 3 来自数据范围
- arange
    - 这个函数返回ndarray对象，包含给定范围内的等间隔值。
- linspace
    - 此函数类似于arange()函数。 在此函数中，指定了范围之间的均匀间隔数量，而不是步长。 此函数的用法如下。
- logspace
    - 此函数返回一个ndarray对象，其中包含在对数刻度上均匀分布的数字。 刻度的开始和结束端点是某个底数的幂，通常为 10。 

In [23]:
#--------------------- arange
"""
这个函数返回ndarray对象，包含给定范围内的等间隔值。

numpy.arange(start, stop, step, dtype)

- start 范围的起始值，默认为0
- stop 范围的终止值(不包含)
- step 两个值的间隔，默认为1
- dtype 返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。 
"""
import numpy as np

print(np.arange(5))  # [0 1 2 3 4]
print(np.arange(5, dtype=float)) # [0. 1. 2. 3. 4.]
print(np.arange(10,20,2)) # [10 12 14 16 18]

#------------------------ linspace
"""
此函数类似于arange()函数。 在此函数中，指定了范围之间的均匀间隔数量，而不是步长。 此函数的用法如下。

numpy.linspace(start, stop, num, endpoint, retstep, dtype)
- start 序列的起始值
- stop 序列的终止值，如果endpoint为true，该值包含于序列中
- num 要生成的等间隔样例数量，默认为50
- endpoint 序列中是否包含stop值，默认为ture
- retstep 如果为true，返回样例，以及连续数字之间的步长
= dtype 输出ndarray的数据类型 
"""
print(np.linspace(10,20,5)) # [10.  12.5 15.  17.5 20. ]
print(np.linspace(10,20,  5, endpoint =  False) ) # [10. 12. 14. 16. 18.]
print(np.linspace(1,2,5, retstep =  True) ) # (array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

#---------------------------- logspace
"""
此函数返回一个ndarray对象，其中包含在对数刻度上均匀分布的数字。 刻度的开始和结束端点是某个底数的幂，通常为 10。

numpy.logscale(start, stop, num, endpoint, base, dtype)

- start 起始值是base ** start
- stop 终止值是base ** stop
- num 范围内的数值数量，默认为50
- endpoint 如果为true，终止值包含在输出数组当中
- base 对数空间的底数，默认为10
- dtype 输出数组的数据类型，如果没有提供，则取决于其它参数 
"""
print(np.logspace(1.0,  2.0, num =  5)) # [ 10.          17.7827941   31.6227766   56.23413252 100.        ]
print(np.logspace(1,10,num =  5,  base  =  2) ) # [   2.            9.51365692   45.254834    215.2694823  1024.        ]




[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[10 12 14 16 18]
[10.  12.5 15.  17.5 20. ]
[10. 12. 14. 16. 18.]
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
[ 10.          17.7827941   31.6227766   56.23413252 100.        ]
[   2.            9.51365692   45.254834    215.2694823  1024.        ]


## 4 随机生成 np.random
- rand(d0, d1, ..., dn) 生成一个0~1之间的随机浮点数或N维浮点数组。
- randn(d0, d1, ..., dn)：生成一个浮点数或N维浮点数组，取数范围：正态分布的随机样本数。
- standard_normal(size=None)：生产一个浮点数或N维浮点数组，取数范围：标准正态分布随机样本
- randint(low, high=None, size=None, dtype='l')：生成一个整数或N维整数数组，取数范围：若high不为None时，取low,high之间随机整数，否则取值0,low之间随机整数。 
- random_sample(size=None)：生成一个0,1之间随机浮点数或N维浮点数组。
- choice(a, size=None, replace=True, p=None)：从序列中获取元素，若a为整数，元素取值为np.range(a)中随机数；若a为数组，取值为a数组元素中随机元素。
- shuffle(x)：对X进行重排序，如果X为多维数组，只沿第一条轴洗牌，输出为None。
- permutation(x)：与numpy.random.shuffle(x)函数功能相同，两者区别：peumutation(x)不会修改X的顺序。


In [34]:
#-------------- rand(d0, d1, ..., dn) 生成一个0~1之间的随机浮点数或N维浮点数组。
#numpy.random.rand(d0, d1, ..., dn)
import numpy as np

np.random.rand()#生成生成[0,1)之间随机浮点数 type  float 
np.random.rand(3)#以为数组  numpy.ndarray 
np.random.rand(2,3)#生成2x3的二维数组 


#---------------- randn(d0, d1, ..., dn)：生成一个浮点数或N维浮点数组，取数范围：正态分布的随机样本数。
#numpy.random.randn(d0, d1, ..., dn)
import numpy as np 
np.random.randn()#1.4872544578730051，不一定是[0,1)之间的随机数
np.random.randn(5)#生成形状为5的一维数组 
np.random.randn(2,3)#生成2x3数组 


#------------- standard_normal(size=None)：生产一个浮点数或N维浮点数组，取数范围：标准正态分布随机样本
import numpy as np 
np.random.standard_normal(2)#array([-2.04606393, -1.05720303])
np.random.standard_normal((2,3))
np.random.standard_normal([2,3]).shape#(2, 3)

#----------------- randint(low, high=None, size=None, dtype='l')：生成一个整数或N维整数数组
"""
取数范围：若high不为None时，取low,high之间随机整数，否则取值0,low之间随机整数。
"""
#numpy.random.randint(low, high=None, size=None, dtype='l')
import numpy as np 
np.random.randint(2)#生成一个[0,2)之间随机整数 
np.random.randint(2, size=5)#array([0, 1, 1, 0, 1]) 
np.random.randint(2, 6)#生成一个[2,6)之间随机整数 
np.random.randint(2, 6,size=5)#生成形状为5的一维整数数组 
np.random.randint(2, size=(2,3))#生成一个2x3整数数组,取数范围：[0,2)随机整数
np.random.randint(2, 6, (2,3))#生成一个2x3整数数组,取值范围：[2,6)随机整数 
np.random.randint(2, dtype='int32')
np.random.randint(2, dtype=np.int32)

#---------------------- random_sample(size=None)
"""
random_sample(size=None)：生成一个0,1之间随机浮点数或N维浮点数组。
"""
#numpy.random.random_sample(size=None)
import numpy as np 
np.random.random_sample()#生成一个[0,1)之间随机浮点数 
np.random.random_sample(2)#生成shape=2的一维数组 
np.random.random_sample((2,))#等同np.random.random_sample(2) 
np.random.random_sample((2,3))#生成2x3数组
np.random.random_sample((3,2,2))#3x2x2数组


#-------------------------- choice(a, size=None, replace=True, p=None)
"""
choice(a, size=None, replace=True, p=None)：从序列中获取元素，若a为整数，
元素取值为np.range(a)中随机数；若a为数组，取值为a数组元素中随机元素。
"""
#numpy.random.choice(a, size=None, replace=True, p=None)
import numpy as np 
np.random.choice(2)#生成一个range(2)中的随机数 
np.random.choice(2,2)#生成一个shape=2一维数组 
np.random.choice(5,(2,3))#生成一个2x3数组 
np.random.choice(np.array(['a','b','c','f']))#生成一个np.array(['a','b','c','f']中随机元素 
np.random.choice(5,(2,3))#生成2x3数组 
np.random.choice(np.array(['a','b','c','f']),(2,3))#生成2x3数组 
np.random.choice(5,p=[0,0,0,0,1])#生成的始终是4
np.random.choice(5,3,p=[0,0.5,0.5,0,0])#生成shape=3的一维数组，元素取值为1或2的随机数

#------------------------ shuffle(x)：对X进行重排序，如果X为多维数组，只沿第一条轴洗牌，输出为None
"""
shuffle(x)：对X进行重排序，如果X为多维数组，只沿第一条轴洗牌，输出为None
"""
#numpy.random.shuffle(x)
import numpy as np
list1 = [1,2,3,4,5]
np.random.shuffle(list1)#输出None
list1#[1, 2, 5, 3, 4],原序列的顺序也被修改
arr = np.arange(9).reshape(3,3)
np.random.shuffle(arr)#对于多维数组，只沿着第一条轴打乱顺序

#--------------------- permutation(x)：
"""
与numpy.random.shuffle(x)函数功能相同，两者区别：peumutation(x)不会修改X的顺序。
"""
#numpy.random.permutation(x)
import numpy as np 
np.random.permutation(5)#生成一个range(5)随机顺序的数组 
list1 = [1,2,3,4]
np.random.permutation(list1)#array([2, 1, 4, 3]) 
arr = np.arange(9)
np.random.permutation(arr)
arr2 = np.arange(9).reshape(3,3)
np.random.permutation(arr2)#对于多维数组，只会沿着第一条轴打乱顺序

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])