## 索引与切片

- 基本访问
- 切片
- 索引

## 1 基本访问

In [7]:
import numpy as np
a = np.arange(10)
a[3]

3

## 2 切片
- slice (start, stop, step)
- :
- ...

In [15]:
import numpy as np

# ----------------- slice
a = np.arange(10)
print(a[slice(2, 7, 2)]) # slice [2 4 6]

# ----------------- start:stop:step 

print(a[2: 7: 2]) # start:stop:step  [2 4 6]
print(a[2:]) # [2 3 4 5 6 7 8 9]
print(a[-2:])


#------------------- ...
"""
切片还可以包括省略号(...)，来使选择元组的长度与数组的维度相同。
如果在行位置使用省略号，它将返回包含行中元素的ndarray。 
"""
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print(a[...,1]) # 第二列  [2 4 5]
print(a[1,...]) # 第二行的元素
print(a[...,1:]) # 第二列及其剩余元素

[2 4 6]
[2 4 6]
[2 3 4 5 6 7 8 9]
[8 9]
[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


## 3 索引
- 整数索引
- 布尔值索引

In [22]:
import numpy as np 

#----------------- 整数索引

x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[[0,1,2],  [0,1,0]]   # [1 4 5]
 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]]) 
rows = np.array([[0,0],[3,3]]) 
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
"""
我们的数组是：                                                                 
[[ 0  1  2]                                                                   
 [ 3  4  5]                                                                   
 [ 6  7  8]                                                                   
 [ 9 10 11]]

这个数组的每个角处的元素是：                                      
[[ 0  2]                                                                      
 [ 9 11]] 
"""

x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
z = x[1:4,1:3] 
y = x[1:4,[1,2]] 
"""
x：
[[ 0  1  2] 
 [ 3  4  5] 
 [ 6  7  8]
 [ 9 10 11]]
z:
[[ 4  5]
 [ 7  8]
 [10 11]]

y:
[[ 4  5]
 [ 7  8]
 [10 11]]

"""

#------------------------ 布尔索引
"""
当结果对象是布尔运算(例如比较运算符)的结果时，将使用此类型的高级索引。
"""
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print(x[x >  5])  # [ 6  7  8  9 10 11]

#  这个例子使用了~(取补运算符)来过滤NaN。
a = np.array([np.nan,  1,2,np.nan,3,4,5]) 
print(a[~np.isnan(a)]) # [ 1.   2.   3.   4.   5.]

# 以下示例显示如何从数组中过滤掉非复数元素。
a = np.array([1,  2+6j,  5,  3.5+5j])  
print(a[np.iscomplex(a)])  # [2.0+6.j  3.5+5.j]

[ 6  7  8  9 10 11]
[1. 2. 3. 4. 5.]
[2. +6.j 3.5+5.j]
