# 排序搜索
- 排序
    - sort 函数返回输入数组的排序副本。
    - argsort 并使用指定排序类型返回数据的索引数组
    - lexsort 该函数返回一个索引数组
- 搜索
    - argmax 这两个函数分别沿给定轴返回最大元素的索引。
    - argmin  这两个函数分别沿给定轴返回最小元素的索引。
    - nonzero 函数返回输入数组中非零元素的索引。
    - where  函数返回输入数组中满足给定条件的元素的索引。
    - extract 函数返回满足任何条件的元素。

## 1 排序
- sort
- argsort
- lexsort

In [9]:
import numpy as np

#--------------------------- sort
"""
numpy.sort(a, axis, kind, order) 
- a 要排序的数组 
- axis 沿着它排序数组的轴 
- kind 默认为'quicksort'(快速排序)
- order 如果数组包含字段，则是要排序的字段 

sort()函数返回输入数组的排序副本。
"""

a = np.array([[3, 7], [9, 1]])
"""
print(np.sort(a))
print(np.sort(a, axis=0))

[[3 7]
 [1 9]]
[[3 1]
 [9 7]]
"""

dt = np.dtype([('name',  'S10'),('age',  int)]) 
a = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt)  
"""
print(np.sort(a, order='name'))

[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]
"""

#--------------------------- argsort
"""
numpy.argsort()函数对输入数组沿给定轴执行间接排序，
并使用指定排序类型返回数据的索引数组。 这个索引数组用于构造排序后的数组。 
"""
x = np.array([3, 1, 2])
y = np.argsort(x)
"""
print(y)
print(x[y])

[1 2 0]
[1 2 3]
"""

#--------------------------- lexsort
"""
函数使用键序列执行间接排序。 键可以看作是电子表格中的一列。
该函数返回一个索引数组，使用它可以获得排序数据。 注意，最后一个键恰好是 sort 的主键。 
"""
nm =  ('raju','anil','ravi','amar') 
dv =  ('f.y.',  's.y.',  's.y.',  'f.y.')  

ind = np.lexsort((dv, nm))
print(ind)
print([nm[i]+","+dv[i] for i in ind])

[3 1 0 2]
['amar,f.y.', 'anil,s.y.', 'raju,f.y.', 'ravi,s.y.']


# 2 搜索
- argmax
- argmin
- nonzero
- where
- extract

In [20]:
import numpy as np

#--------------------------- argmax
a = np.array([[30, 40, 70], [80, 20, 10], [50, 90, 60]])
"""
print(np.argmax(a))
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

7
[1 2 0]
[2 0 1]
"""

#--------------------------- argmin
"""
print(np.argmin(a))
print(np.argmin(a, axis=0))
print(np.argmin(a, axis=1))

5
[0 1 1]
[0 2 0]
"""

#--------------------------- nonzero
"""
numpy.nonzero()函数返回输入数组中非零元素的索引。
"""
a = np.array([[30, 40, 0], [0, 20, 10], [50, 0, 60]])
"""
print(np.nonzero(a))

# 两个数组分别代表2个轴的坐标
(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))
"""

#--------------------------- where
"""
where()函数返回输入数组中满足给定条件的元素的索引。
"""
x = np.arange(9.).reshape(3, 3)
y = np.where(x > 3)
"""
print(x)
print(y)
print(x[y])

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))
[4. 5. 6. 7. 8.]
"""

#--------------------------- extract
"""
extract()函数返回满足任何条件的元素。
"""
x = np.arange(9.).reshape(3, 3)
condition = np.mod(x, 2)==0
"""
print(x)
print(condition)
print(np.extract(condition, x))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ True False  True]
 [False  True False]
 [ True False  True]]
[0. 2. 4. 6. 8.]
"""
print()

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ True False  True]
 [False  True False]
 [ True False  True]]
[0. 2. 4. 6. 8.]
