

<font size=5>__数据预处理__</font>

- 数据标准化
- 归一化
- 二值化

In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler 

In [2]:
df = pd.read_csv("/Users/zhouwencheng/Desktop/Grass/05 AI/05 jupyter/10 data/creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

# 标准化

- [0, 1] 标准化
- Z-score 标准化

## [0, 1]标准化
- x = (x - min(x)/(max(x) - min(x))

In [2]:
import numpy as np

In [3]:
def data_normalization_0(x):
    x =(x - np.min(x)) / (np.max(x) - np.min(x))
    return x

In [8]:
def data_normalization_1(x, min, max):
    """[0,1] normaliaztion"""
    x = (x - min) / (max - min)
    return x

In [54]:
x = np.array([
    [2, 4, 5],
    [3, 4, 1],
    [5, 6, 9]
])
x = x.astype(float)
x

array([[2., 4., 5.],
       [3., 4., 1.],
       [5., 6., 9.]])

In [55]:
x1 = data_normalization_0(x)
x1

array([[0.125, 0.375, 0.5  ],
       [0.25 , 0.375, 0.   ],
       [0.5  , 0.625, 1.   ]])

In [56]:
x2 = data_normalization_1(x, np.min(x), np.max(x))
x2

array([[0.125, 0.375, 0.5  ],
       [0.25 , 0.375, 0.   ],
       [0.5  , 0.625, 1.   ]])

## 标准化 (sklearn.preprocessing)

In [50]:
from sklearn import preprocessing

In [53]:

preprocessing.scale(x)

array([[-1.06904497, -0.70710678,  0.        ],
       [-0.26726124, -0.70710678, -1.22474487],
       [ 1.33630621,  1.41421356,  1.22474487]])

# 归一化
- 'Amount' 列的数据太大了，需要进行归一化处理

In [4]:
ss = StandardScaler().fit_transform(df.Amount.values.reshape(-1, 1))
ss

array([[ 0.24496426],
       [-0.34247454],
       [ 1.16068593],
       ...,
       [-0.0818393 ],
       [-0.31324853],
       [ 0.51435531]])

# 二值化

In [59]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelBinarizer

In [60]:
testdata = pd.DataFrame({'pet': ['cat', 'dog', 'dog', 'fish'],'age': [4 , 6, 3, 3],'salary':[4, 5, 1, 1]})
testdata

pet  age  salary
0   cat    4       4
1   dog    6       5
2   dog    3       1
3  fish    3       1

## LabelBinarizer()
- 直接调用 LabelBinarizer()，用于数字和字符串都是可以的

In [76]:
pet_binarlizer = LabelBinarizer().fit_transform(testdata.pet) 
pet = pd.DataFrame(pet_binarlizer, columns=testdata.columns) 
pet

pet  age  salary
0    1    0       0
1    0    1       0
2    0    1       0
3    0    0       1

## LabelEncoder() + OneHotEncoder(）

In [80]:
pet = OneHotEncoder(sparse=False).fit_transform(LabelEncoder().fit_transform(testdata['pet']).reshape(-1,1))
pet = pd.DataFrame(pet,columns=['pet_cat','pet_dog','pet_fish'])
pet

/Users/zhouwencheng/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


pet_cat  pet_dog  pet_fish
0      1.0      0.0       0.0
1      0.0      1.0       0.0
2      0.0      1.0       0.0
3      0.0      0.0       1.0