In [1]:
s1 = "John likes to watch movies.Mary likes too"
s2 = "John also likes to watch football games"

In [28]:
import re
s1 = re.sub("[.,!:]", " ", s1)
s2 = re.sub("[.,!:]", " ", s2)

s1_l = [item for item in s1.split(' ') if len(item)>0]
s2_l = [item for item in s2.split(' ') if len(item)>0]
words = s1_l + s2_l 

In [29]:
word_index = {}
index = 0
for word in words:
    if word not in word_index:
        word_index[word] = index
        index += 1

# numpy 转化

In [33]:
import numpy as np

def s_to_one_hot(sentence, word_dict): 
    table = np.zeros(shape=(len(sentence), len(word_dict)))
    for i in range(len(sentence)):
        item = sentence[i] 
        index = word_dict.get(item, 0)
        table[i][index] = 1
    return table

In [34]:
s_to_one_hot(s1_l, word_index)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

# sklearn

In [37]:
from sklearn import preprocessing

In [39]:
import re

s1 = "John likes to watch movies.Mary likes too"
s2 = "John also likes to watch football games"

s1 = re.sub("[.,!:]", " ", s1)
s2 = re.sub("[.,!:]", " ", s2)
s1_l = [item for item in s1.split(' ') if len(item)>0]
s2_l = [item for item in s2.split(' ') if len(item)>0]
words = s1_l + s2_l

In [47]:
# 数据预处理
import numpy as np
words = np.array(words).reshape(-1, 1)
s1_l = np.array(s1_l).reshape(-1, 1)
s2_l = np.array(s2_l).reshape(-1, 1)

enc = preprocessing.OneHotEncoder()
enc.fit(words)
enc.transform(s1_l).toarray()

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

# keras （处理数字型）

In [59]:
from keras.utils import to_categorical

In [68]:
to_categorical([2, 1])

array([[0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

In [67]:
to_categorical([2, 20])

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1.]], dtype=float32)